apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nginx-operator-system
  name: waf-api
spec:
  selector:
    matchLabels:
      app: waf-api
  replicas: 1
  template:
    metadata:
      labels:
        app: waf-api
    spec:
      serviceAccountName: waf-service-account
      containers:
      - name: waf-api
        image: arthurcgc/waf:v1
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: nginx-operator-system
  name: waf-api
spec:
  type: NodePort
  selector:
    app: waf-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
